/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package sk.matt.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;
import sk.matt.model.OrganizationData;

import javax.annotation.Generated;
import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-31T01:21:49.483040+02:00[Europe/Bratislava]", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "organizations", description = "the organizations API")
public interface OrganizationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /organizations : Get all organizations
     *
     * @return A list of organizations (status code 200)
     */
    @Operation(
        operationId = "organizationsGet",
        summary = "Get all organizations",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of organizations", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OrganizationData.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/organizations",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<OrganizationData>> organizationsGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"person\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] } ], \"contact\" : { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, \"name\" : \"name\", \"id\" : 0 }, { \"person\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] } ], \"contact\" : { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, \"name\" : \"name\", \"id\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /organizations/{id} : Delete an organization by ID
     *
     * @param id  (required)
     * @return Deleted (status code 204)
     *         or Organization not found (status code 404)
     */
    @Operation(
        operationId = "organizationsIdDelete",
        summary = "Delete an organization by ID",
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted"),
            @ApiResponse(responseCode = "404", description = "Organization not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/organizations/{id}"
    )
    
    default ResponseEntity<Void> organizationsIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /organizations/{id} : Get an organization by ID
     *
     * @param id  (required)
     * @return An organization (status code 200)
     *         or Organization not found (status code 404)
     */
    @Operation(
        operationId = "organizationsIdGet",
        summary = "Get an organization by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "An organization", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganizationData.class))
            }),
            @ApiResponse(responseCode = "404", description = "Organization not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/organizations/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<OrganizationData> organizationsIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"person\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] } ], \"contact\" : { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, \"name\" : \"name\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /organizations/{id} : Update an organization by ID
     *
     * @param id  (required)
     * @param organizationData  (required)
     * @return Updated (status code 200)
     *         or Organization not found (status code 404)
     */
    @Operation(
        operationId = "organizationsIdPut",
        summary = "Update an organization by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganizationData.class))
            }),
            @ApiResponse(responseCode = "404", description = "Organization not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/organizations/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<OrganizationData> organizationsIdPut(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "OrganizationData", description = "", required = true) @Valid @RequestBody OrganizationData organizationData
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"person\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] } ], \"contact\" : { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, \"name\" : \"name\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /organizations : Create an organization
     *
     * @param organizationData  (required)
     * @return Created organization successfully (status code 201)
     */
    @Operation(
        operationId = "organizationsPost",
        summary = "Create an organization",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created organization successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganizationData.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/organizations",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<OrganizationData> organizationsPost(
        @Parameter(name = "OrganizationData", description = "", required = true) @Valid @RequestBody OrganizationData organizationData
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"person\" : [ { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] }, { \"firstName\" : \"firstName\", \"lastName\" : \"lastName\", \"dateOfBirth\" : \"2000-01-23\", \"id\" : 0, \"contacts\" : [ { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" } ] } ], \"contact\" : { \"phoneNumber\" : \"phoneNumber\", \"address\" : \"address\", \"email\" : \"email\" }, \"name\" : \"name\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
